# Generated by Django 4.1.3 on 2022-11-17 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superauth', '0003_alter_customusermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('e7225464-1e7c-4187-8a2b-c0efde5013be'), editable=False, primary_key=True, serialize=False),
        ),
    ]
