# Generated by Django 4.1.3 on 2022-11-17 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superauth', '0004_alter_customusermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_id',
            field=models.CharField(default=uuid.UUID('7bae3b96-6db1-4471-afa5-96fbe13bff4c'), editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
