# Generated by Django 4.0.4 on 2022-05-05 15:48

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='state',
            field=django_fsm.FSMField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Re Opened', 'Re Opened'), ('Closed', 'Closed')], default='Open', max_length=50, protected=True),
        ),
    ]
