# Generated by Django 4.0.4 on 2022-10-30 10:20

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todotask_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='state',
            field=django_fsm.FSMField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Under Review', 'Under Review'), ('Re Opened', 'Re Opened'), ('Closed', 'Closed')], default='Open', max_length=50, protected=True),
        ),
    ]
